#ifndef LIFEGAMECORE_GLOBAL_HPP
#define LIFEGAMECORE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(LIFEGAMECORE_LIBRARY)
#  define LIFEGAMECORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIFEGAMECORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIFEGAMECORE_GLOBAL_HPP
