#ifndef LIFEGAMECORE2_GLOBAL_HPP
#define LIFEGAMECORE2_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(LIFEGAMECORE2_LIBRARY)
#  define LIFEGAMECORE2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIFEGAMECORE2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LIFEGAMECORE2_GLOBAL_HPP
